
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.dani.appmovil.parserXml;

/** CUP generated class containing symbol constants. */
public class ParserXmlSym {
  /* terminals */
  public static final int ERRORS = 10;
  public static final int TOKENERROR = 26;
  public static final int DESCRIPTION = 12;
  public static final int INTERROGACION = 39;
  public static final int BRICK_COLOR = 33;
  public static final int WORLDS = 13;
  public static final int ENTERO = 2;
  public static final int TARGETS = 21;
  public static final int BOX_COLOR = 30;
  public static final int TARGET_COLOR = 32;
  public static final int ROWS = 16;
  public static final int CONFIG = 18;
  public static final int SIG_COMILLAS = 43;
  public static final int TYPE = 29;
  public static final int BOX_ON_TARGET_COLOR = 31;
  public static final int BOARD = 19;
  public static final int ERR = 11;
  public static final int VERSION = 6;
  public static final int HALL = 3;
  public static final int HALL_COLOR = 34;
  public static final int DECIMAL = 40;
  public static final int EOF = 0;
  public static final int BRICK = 4;
  public static final int PLAYER = 22;
  public static final int PALABRA = 5;
  public static final int error = 1;
  public static final int SIG_IGUAL = 37;
  public static final int WORLD = 14;
  public static final int SIGNO_C = 42;
  public static final int ERROR = 45;
  public static final int SIGNO_A = 41;
  public static final int NAME = 15;
  public static final int LEXEMA = 23;
  public static final int COLS = 17;
  public static final int LITERAL = 7;
  public static final int BOXES = 20;
  public static final int ENCODING = 8;
  public static final int ALL = 44;
  public static final int XML = 38;
  public static final int UNDEFINED_COLOR = 35;
  public static final int DIVISION = 9;
  public static final int LINEA = 24;
  public static final int COLUMNA = 25;
  public static final int PLAYER_COLOR = 36;
  public static final int POS_Y = 27;
  public static final int POS_X = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "HALL",
  "BRICK",
  "PALABRA",
  "VERSION",
  "LITERAL",
  "ENCODING",
  "DIVISION",
  "ERRORS",
  "ERR",
  "DESCRIPTION",
  "WORLDS",
  "WORLD",
  "NAME",
  "ROWS",
  "COLS",
  "CONFIG",
  "BOARD",
  "BOXES",
  "TARGETS",
  "PLAYER",
  "LEXEMA",
  "LINEA",
  "COLUMNA",
  "TOKENERROR",
  "POS_Y",
  "POS_X",
  "TYPE",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "PLAYER_COLOR",
  "SIG_IGUAL",
  "XML",
  "INTERROGACION",
  "DECIMAL",
  "SIGNO_A",
  "SIGNO_C",
  "SIG_COMILLAS",
  "ALL",
  "ERROR"
  };
}

