
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.dani.appmovil.objects;

/** CUP generated class containing symbol constants. */
public class ParserMovSym {
  /* terminals */
  public static final int MULTIPLY = 13;
  public static final int DECIMAL = 11;
  public static final int DIVISION = 15;
  public static final int SUMA = 12;
  public static final int UP = 8;
  public static final int L_PARENT = 16;
  public static final int R_PARENT = 17;
  public static final int FLOOR = 5;
  public static final int CEIL = 6;
  public static final int NUM = 10;
  public static final int RIGHT = 4;
  public static final int LEFT = 7;
  public static final int EOF = 0;
  public static final int PUSH = 3;
  public static final int error = 1;
  public static final int DOWN = 2;
  public static final int PUNTO_COMA = 9;
  public static final int RESTA = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOWN",
  "PUSH",
  "RIGHT",
  "FLOOR",
  "CEIL",
  "LEFT",
  "UP",
  "PUNTO_COMA",
  "NUM",
  "DECIMAL",
  "SUMA",
  "MULTIPLY",
  "RESTA",
  "DIVISION",
  "L_PARENT",
  "R_PARENT"
  };
}

